### ISSUE TITLE
SET_PENDING_OWNER() emits incorrect topic1

### ISSUE THREAD

**Issue by devtooligan** [byterocket/TSOwnabe-Huff#2]
It's emitting the pending owner address when it sb the current owner.

**Comment by pmerkleplant** [comment]
This is actually the intended behavior. The event emits the `oldPendingOwner` and `newPendingOwner`.
I refactored the `setPendingOwner` test to make this more clear, see [here](https://github.com/byterocket/TSOwnabe-Huff/blob/main/test/TSOwnable.t.sol#L62).

Many thanks anyway. Glad to see folks studying our code! ❤️ 

In case you think the event should emit the current owner instead of the last pending owner, or maybe both, feel free to reopen this issue!
